const  articleContent = [
    {
    name:"learn-react",
    title:"The fastest way to learn react",
    thumbnil:"/images/blog1.png",
    content:[
        `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil magnam officia ipsum ex corrupti cumque qui reiciendis, quia quae esse dolore reprehenderit consectetur ducimus explicabo maxime. Repudiandae aspernatur labore necessitatibus rem eum molestias, quidem iure illum laboriosam, nemo, fuga eveniet quibusdam fugiat excepturi qui pariatur molestiae cumque. Labore voluptatum quos culpa natus quas eaque corporis quidem officia, tenetur, alias minus saepe ut. Perspiciatis, sapiente quos sit temporibus tempore, consectetur nobis provident corrupti, culpa quasi similique rerum dicta nostrum obcaecati enim. Aliquam, sunt quidem amet fugiat maxime voluptate vitae tenetur, minima similique sapiente atque, esse hic debitis iusto eveniet corrupti magni.`,
        `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil magnam officia ipsum ex corrupti cumque qui reiciendis, quia quae esse dolore reprehenderit consectetur ducimus explicabo maxime. Repudiandae aspernatur labore necessitatibus rem eum molestias, quidem iure illum laboriosam, nemo, fuga eveniet quibusdam fugiat excepturi qui pariatur molestiae cumque. Labore voluptatum quos culpa natus quas eaque corporis quidem officia, tenetur, alias minus saepe ut. Perspiciatis, sapiente quos sit temporibus tempore, consectetur nobis provident corrupti, culpa quasi similique rerum dicta nostrum obcaecati enim. Aliquam, sunt quidem amet fugiat maxime voluptate vitae tenetur, minima similique sapiente atque, esse hic debitis iusto eveniet corrupti magni.`,
        `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil magnam officia ipsum ex corrupti cumque qui reiciendis, quia quae esse dolore reprehenderit consectetur ducimus explicabo maxime. Repudiandae aspernatur labore necessitatibus rem eum molestias, quidem iure illum laboriosam, nemo, fuga eveniet quibusdam fugiat excepturi qui pariatur molestiae cumque. Labore voluptatum quos culpa natus quas eaque corporis quidem officia, tenetur, alias minus saepe ut. Perspiciatis, sapiente quos sit temporibus tempore, consectetur nobis provident corrupti, culpa quasi similique rerum dicta nostrum obcaecati enim. Aliquam, sunt quidem amet fugiat maxime voluptate vitae tenetur, minima similique sapiente atque, esse hic debitis iusto eveniet corrupti magni.`
    ]

},
    {
    name:"learn-express",
    title:"The fastest way to learn express",
    thumbnil:"/images/blog1.png",
    content:[
        `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil magnam officia ipsum ex corrupti cumque qui reiciendis, quia quae esse dolore reprehenderit consectetur ducimus explicabo maxime. Repudiandae aspernatur labore necessitatibus rem eum molestias, quidem iure illum laboriosam, nemo, fuga eveniet quibusdam fugiat excepturi qui pariatur molestiae cumque. Labore voluptatum quos culpa natus quas eaque corporis quidem officia, tenetur, alias minus saepe ut. Perspiciatis, sapiente quos sit temporibus tempore, consectetur nobis provident corrupti, culpa quasi similique rerum dicta nostrum obcaecati enim. Aliquam, sunt quidem amet fugiat maxime voluptate vitae tenetur, minima similique sapiente atque, esse hic debitis iusto eveniet corrupti magni.`,
        `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil magnam officia ipsum ex corrupti cumque qui reiciendis, quia quae esse dolore reprehenderit consectetur ducimus explicabo maxime. Repudiandae aspernatur labore necessitatibus rem eum molestias, quidem iure illum laboriosam, nemo, fuga eveniet quibusdam fugiat excepturi qui pariatur molestiae cumque. Labore voluptatum quos culpa natus quas eaque corporis quidem officia, tenetur, alias minus saepe ut. Perspiciatis, sapiente quos sit temporibus tempore, consectetur nobis provident corrupti, culpa quasi similique rerum dicta nostrum obcaecati enim. Aliquam, sunt quidem amet fugiat maxime voluptate vitae tenetur, minima similique sapiente atque, esse hic debitis iusto eveniet corrupti magni.`,
        `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil magnam officia ipsum ex corrupti cumque qui reiciendis, quia quae esse dolore reprehenderit consectetur ducimus explicabo maxime. Repudiandae aspernatur labore necessitatibus rem eum molestias, quidem iure illum laboriosam, nemo, fuga eveniet quibusdam fugiat excepturi qui pariatur molestiae cumque. Labore voluptatum quos culpa natus quas eaque corporis quidem officia, tenetur, alias minus saepe ut. Perspiciatis, sapiente quos sit temporibus tempore, consectetur nobis provident corrupti, culpa quasi similique rerum dicta nostrum obcaecati enim. Aliquam, sunt quidem amet fugiat maxime voluptate vitae tenetur, minima similique sapiente atque, esse hic debitis iusto eveniet corrupti magni.`
    ]

},
    {
    name:"learn-flutter",
    title:"The fastest way to learn fluter",
    thumbnil:"/images/blog1.jpeg",
    content:[
        `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil magnam officia ipsum ex corrupti cumque qui reiciendis, quia quae esse dolore reprehenderit consectetur ducimus explicabo maxime. Repudiandae aspernatur labore necessitatibus rem eum molestias, quidem iure illum laboriosam, nemo, fuga eveniet quibusdam fugiat excepturi qui pariatur molestiae cumque. Labore voluptatum quos culpa natus quas eaque corporis quidem officia, tenetur, alias minus saepe ut. Perspiciatis, sapiente quos sit temporibus tempore, consectetur nobis provident corrupti, culpa quasi similique rerum dicta nostrum obcaecati enim. Aliquam, sunt quidem amet fugiat maxime voluptate vitae tenetur, minima similique sapiente atque, esse hic debitis iusto eveniet corrupti magni.`,
        `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil magnam officia ipsum ex corrupti cumque qui reiciendis, quia quae esse dolore reprehenderit consectetur ducimus explicabo maxime. Repudiandae aspernatur labore necessitatibus rem eum molestias, quidem iure illum laboriosam, nemo, fuga eveniet quibusdam fugiat excepturi qui pariatur molestiae cumque. Labore voluptatum quos culpa natus quas eaque corporis quidem officia, tenetur, alias minus saepe ut. Perspiciatis, sapiente quos sit temporibus tempore, consectetur nobis provident corrupti, culpa quasi similique rerum dicta nostrum obcaecati enim. Aliquam, sunt quidem amet fugiat maxime voluptate vitae tenetur, minima similique sapiente atque, esse hic debitis iusto eveniet corrupti magni.`,
        `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil magnam officia ipsum ex corrupti cumque qui reiciendis, quia quae esse dolore reprehenderit consectetur ducimus explicabo maxime. Repudiandae aspernatur labore necessitatibus rem eum molestias, quidem iure illum laboriosam, nemo, fuga eveniet quibusdam fugiat excepturi qui pariatur molestiae cumque. Labore voluptatum quos culpa natus quas eaque corporis quidem officia, tenetur, alias minus saepe ut. Perspiciatis, sapiente quos sit temporibus tempore, consectetur nobis provident corrupti, culpa quasi similique rerum dicta nostrum obcaecati enim. Aliquam, sunt quidem amet fugiat maxime voluptate vitae tenetur, minima similique sapiente atque, esse hic debitis iusto eveniet corrupti magni.`
    ]

},
    {
    name:"learn-mongo",
    title:"The fastest way to learn mogno",
    thumbnil:"/images/blog1.png",
    content:[
        `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil magnam officia ipsum ex corrupti cumque qui reiciendis, quia quae esse dolore reprehenderit consectetur ducimus explicabo maxime. Repudiandae aspernatur labore necessitatibus rem eum molestias, quidem iure illum laboriosam, nemo, fuga eveniet quibusdam fugiat excepturi qui pariatur molestiae cumque. Labore voluptatum quos culpa natus quas eaque corporis quidem officia, tenetur, alias minus saepe ut. Perspiciatis, sapiente quos sit temporibus tempore, consectetur nobis provident corrupti, culpa quasi similique rerum dicta nostrum obcaecati enim. Aliquam, sunt quidem amet fugiat maxime voluptate vitae tenetur, minima similique sapiente atque, esse hic debitis iusto eveniet corrupti magni.`,
        `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil magnam officia ipsum ex corrupti cumque qui reiciendis, quia quae esse dolore reprehenderit consectetur ducimus explicabo maxime. Repudiandae aspernatur labore necessitatibus rem eum molestias, quidem iure illum laboriosam, nemo, fuga eveniet quibusdam fugiat excepturi qui pariatur molestiae cumque. Labore voluptatum quos culpa natus quas eaque corporis quidem officia, tenetur, alias minus saepe ut. Perspiciatis, sapiente quos sit temporibus tempore, consectetur nobis provident corrupti, culpa quasi similique rerum dicta nostrum obcaecati enim. Aliquam, sunt quidem amet fugiat maxime voluptate vitae tenetur, minima similique sapiente atque, esse hic debitis iusto eveniet corrupti magni.`,
        `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil magnam officia ipsum ex corrupti cumque qui reiciendis, quia quae esse dolore reprehenderit consectetur ducimus explicabo maxime. Repudiandae aspernatur labore necessitatibus rem eum molestias, quidem iure illum laboriosam, nemo, fuga eveniet quibusdam fugiat excepturi qui pariatur molestiae cumque. Labore voluptatum quos culpa natus quas eaque corporis quidem officia, tenetur, alias minus saepe ut. Perspiciatis, sapiente quos sit temporibus tempore, consectetur nobis provident corrupti, culpa quasi similique rerum dicta nostrum obcaecati enim. Aliquam, sunt quidem amet fugiat maxime voluptate vitae tenetur, minima similique sapiente atque, esse hic debitis iusto eveniet corrupti magni.`
    ]

},
    {
    name:"learn-node",
    title:"The fastest way to learn node",
    thumbnil:"/images/blog1.jpeg",
    content:[
        `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil magnam officia ipsum ex corrupti cumque qui reiciendis, quia quae esse dolore reprehenderit consectetur ducimus explicabo maxime. Repudiandae aspernatur labore necessitatibus rem eum molestias, quidem iure illum laboriosam, nemo, fuga eveniet quibusdam fugiat excepturi qui pariatur molestiae cumque. Labore voluptatum quos culpa natus quas eaque corporis quidem officia, tenetur, alias minus saepe ut. Perspiciatis, sapiente quos sit temporibus tempore, consectetur nobis provident corrupti, culpa quasi similique rerum dicta nostrum obcaecati enim. Aliquam, sunt quidem amet fugiat maxime voluptate vitae tenetur, minima similique sapiente atque, esse hic debitis iusto eveniet corrupti magni.`,
        `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil magnam officia ipsum ex corrupti cumque qui reiciendis, quia quae esse dolore reprehenderit consectetur ducimus explicabo maxime. Repudiandae aspernatur labore necessitatibus rem eum molestias, quidem iure illum laboriosam, nemo, fuga eveniet quibusdam fugiat excepturi qui pariatur molestiae cumque. Labore voluptatum quos culpa natus quas eaque corporis quidem officia, tenetur, alias minus saepe ut. Perspiciatis, sapiente quos sit temporibus tempore, consectetur nobis provident corrupti, culpa quasi similique rerum dicta nostrum obcaecati enim. Aliquam, sunt quidem amet fugiat maxime voluptate vitae tenetur, minima similique sapiente atque, esse hic debitis iusto eveniet corrupti magni.`,
        `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil magnam officia ipsum ex corrupti cumque qui reiciendis, quia quae esse dolore reprehenderit consectetur ducimus explicabo maxime. Repudiandae aspernatur labore necessitatibus rem eum molestias, quidem iure illum laboriosam, nemo, fuga eveniet quibusdam fugiat excepturi qui pariatur molestiae cumque. Labore voluptatum quos culpa natus quas eaque corporis quidem officia, tenetur, alias minus saepe ut. Perspiciatis, sapiente quos sit temporibus tempore, consectetur nobis provident corrupti, culpa quasi similique rerum dicta nostrum obcaecati enim. Aliquam, sunt quidem amet fugiat maxime voluptate vitae tenetur, minima similique sapiente atque, esse hic debitis iusto eveniet corrupti magni.`
    ]

},
]
export  default articleContent